# wrangler.toml - Supporting both Pages and Workers
name = "real-estate-accounting"

# For Cloudflare Workers
main = "./dist/_worker.js"
compatibility_date = "2025-05-16"

# Pages configuration
# Don't include pages_build_output_dir - use the following instead:
[site]
bucket = "./dist"

# Database and storage bindings
[[d1_databases]]
binding = "DB"
database_name = "real-estate-accounting-db"
database_id = "3198e043-80f0-4d51-b849-4d3a78380039"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "SESSION"
id = "b4591e5e144843f6837619edb455c52c"

[[kv_namespaces]]
binding = "REPORTS_CACHE"
id = "a5892e1bcc7b43d8ad84b9ffa89c59c1"

[[r2_buckets]]
binding = "DOCUMENTS"
bucket_name = "real-estate-documents"

# Environment variables
[vars]
ENVIRONMENT = "production"

# For dev environments
[dev]
port = 8788